name: SICAE
description: Sistema Integral de Control de Asistencia Escolar.
version: 2.1.1
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
#  responsive_framework:
#    path: ../
  # Uncomment to build standalone project.
  responsive_framework: ^1.5.1
  #google_fonts: ^6.2.1
  animations: ^2.0.11
  loading_gifs: ^0.3.0
  url_launcher: ^6.3.0 # Requires setup.
  supabase: ^2.6.3
  qr_flutter: ^4.1.0
  qr: ^3.0.1
  pdf: ^3.11.3
  printing: ^5.14.2
  csv: ^6.0.0
  sqlite3_flutter_libs: ^0.5.33
  ffi: ^2.1.0
  connectivity_plus: ^6.1.4
  sqflite_common_ffi: ^2.3.4+4
  path_provider: ^2.1.5
  excel: ^4.0.6
  permission_handler: ^12.0.0+1
  process_run: ^0.13.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo26s.png"
  image_path_android: "assets/images/logo26s.png"
  image_path_ios: "assets/images/logo26s.png"
  adaptive_icon_background: "#FFFFFFFF"
  adaptive_icon_foreground: "assets/images/logo26s.png"
  web:
    generate: true
  macos:
    generate: true
  windows:
    generate: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/database/mi_base.db